apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: statestore
  namespace: petclinic
spec:
  type: state.azure.tablestorage
  version: v1
  metadata:
    - name: accountName
      value: <REPLACE-WITH-ACCOUNT-NAME>
    - name: accountKey
      value: <REPLACE-WITH-ACCOUNT-KEY>
    - name: tableName
      value: <REPLACE-WITH-TABLE-NAME>
